<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoffeeJournal.Application\CoffeeJournal.Application.csproj" />
    <ProjectReference Include="..\CoffeeJournal.Domain\CoffeeJournal.Domain.csproj" />
  </ItemGroup>

</Project>
